/*
 * This file is generated by jOOQ.
 */
package com.generator;


import com.generator.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = com.generator.tables.Users.USERS;
}
